
// This file has been generated by the GUI designer. Do not modify.
namespace CCategoria
{
	public partial class CategoriaView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CCategoria.CategoriaView
			this.Name = "CCategoria.CategoriaView";
			this.Title = global::Mono.Unix.Catalog.GetString ("CategoriaView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
