/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '24/02/16 9:41' with Gradle 2.6
 *
 * @author mati, @date 24/02/16 9:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
